---
layout:  post
title: "The Priceonomics Data Puzzle: TreefortBnb"
comments:  false
published:  true
author: "Cyrus M"
categories: [R]
output:
  html_document:
    mathjax:  default
    fig_caption:  true
---

## Which Are the Most Expensive Cities in America to Book a Tree Fort?

It's the year 2020 and the sharing-economy is in full gear. Everything from hosting city dinners to ride-sharing the great outdoors is fair game. Capitalizing on their own interests and experience, eight-year-old startup prodigees, Sally Hershfield and Felicia Alvarez, have taken the sharing-economy by storm with their ever-growing TreefortBnB enterprise. 

Their nascent business venture has become such a hit that industry powerhouse AirBnb has not only taken notice but also action. They've identified markets where TreefortBnb has expanded most successfully and it's been rumored that AirBnb aims to undercut their marketshare by providing incentives that push their users to advertise more competitive prices. 

Using data obtained from Priceonomics, I've identified the median price of tree fort rentals for the top 100 cities with the most units on the market. Indianapolis IN, Malibu CA, and Park City UT are the most expensive cities in the US to rent a tree fort by median pricing, something AirBnb hopes to use to its own advantage by provding lower cost classical home alternatives.

```{r, fig.align='right', fig.width=10, message=FALSE, comment=FALSE, error=FALSE, warning=FALSE}
##Load Dependencies
library(pipeR)
library(dplyr)
library(formattable)

##URL to download data
url<-"https://s3.amazonaws.com/pix-media/Data+for+TreefortBnB+Puzzle.csv"

#Read in data and aggregate # of units by city and subset to top 100
df1 <- url %>%
  read.csv(col.names=c("ID","City","State","Price","Reviews")) %>%
  group_by(State, City) %>%
  summarize(Unit_Sum=n()) %>% 
  arrange(desc(Unit_Sum)) %>%
  head(100) 

#Read in data again and obtain median rental price by city
df2 <- url %>%
  read.csv(col.names=c("ID","City","State","Price","Reviews")) %>%
  group_by(State, City) %>%
  summarize(Price_Median=median(Price)) %>%
  arrange(desc(Price_Median)) 

#Merge two data frames
df3 <-merge(df1, df2, by=c("City", "State"), all.x=TRUE, all.y=FALSE)
df3<-arrange(df3, desc(Price_Median))

#Rename columns
colnames(df3)[3]<-"Unit Total"
colnames(df3)[4]<-"Median Price"

#Produce output table in html
formattable(df3, list(
  'Median Price' = color_bar("orange")))
```




